name: Golang Tests

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14' # The Go version to download (if necessary) and use.
    - name: Install and run Redis
      run: |
        sudo apt-get install redis
    - run: go test


